name: Prepare Wiki pages for Oviva Wiki

on:
  gollum:
  workflow_dispatch:

jobs:
  prepare_wiki_for_oviva_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Check out wiki repository
        uses: actions/checkout@v2
        with:
          repository: 'yamsergey/pyautoproxy.wiki.git'
          ref: 'master'
          path: 'pyautoproxy.wiki'
      - run: cd $GITHUB_WORKSPACE/pyautoproxy.wiki    
      - run: git config --global user.name 'Wiki'
      - run: git config --global user.email 'yamsergey@gmail.com'
      - run: git branch -a
      - run: git checkout wiki
      - run: git merge master
      - run: find ./docs -depth -name "*.asciidoc" -exec sh -c 'mv "$1" "${1%.asciidoc}.adoc"' _ {} \;
      - run: find ./docs -type f -exec sed -i '' 's/.asciidoc/.adoc/g' {} +
      - run: git add -all
      - run: git commit -m "Replace .asciidoc with .adoc in files and content"
      - run: git push
